require_relative 'validators/base'
require_relative 'validators/bug'
require_relative 'validators/dependency'
require_relative 'validators/improvement'
require_relative 'validators/minor_improvement'
